services:
  - type: web
    name: medical-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: GEMINI_API_KEY
        value: your_key_here
    disk:
      name: chroma-store
      mountPath: /mnt/data
      sizeGB: 2
